apiVersion: apps/v1
kind: Deployment
metadata:
  name: si-notepad
  labels:
    app: si-notepad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: si-notepad
  template:
    metadata:
      labels:
        app: si-notepad
    spec:
      containers:
      - name: si-notepad
        image:  ksw2137/si-notepad:3a43609ffa847e429bada6f652e02879640cbe8a
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: si-notepad
spec:
  selector:
    app: si-notepad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP